name: volanteo_tracker
description: App de tracking para volanteo.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  connectivity_plus: ^6.0.5
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  flutter_background_service: ^5.0.10
  flutter_local_notifications: ^17.2.3
  shared_preferences: ^2.3.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
